# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from paws_client.models.v1_daemons_get200_response_daemons_inner_stats import V1DaemonsGet200ResponseDaemonsInnerStats
from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger import V1DaemonsGet200ResponseDaemonsInnerTrigger
from paws_client.models.v1_daemons_post_request_governance import V1DaemonsPostRequestGovernance
from paws_client.models.v1_daemons_role_get200_response_recent_sessions_inner import V1DaemonsRoleGet200ResponseRecentSessionsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1DaemonsRoleGet200Response(BaseModel):
    """
    V1DaemonsRoleGet200Response
    """ # noqa: E501
    role: Annotated[str, Field(min_length=1, strict=True)]
    description: StrictStr
    status: StrictStr
    trigger: V1DaemonsGet200ResponseDaemonsInnerTrigger
    stats: V1DaemonsGet200ResponseDaemonsInnerStats
    governance: V1DaemonsPostRequestGovernance
    recent_sessions: List[V1DaemonsRoleGet200ResponseRecentSessionsInner] = Field(alias="recentSessions")
    __properties: ClassVar[List[str]] = ["role", "description", "status", "trigger", "stats", "governance", "recentSessions"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'paused', 'stopped']):
            raise ValueError("must be one of enum values ('active', 'paused', 'stopped')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1DaemonsRoleGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trigger
        if self.trigger:
            _dict['trigger'] = self.trigger.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stats
        if self.stats:
            _dict['stats'] = self.stats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of governance
        if self.governance:
            _dict['governance'] = self.governance.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recent_sessions (list)
        _items = []
        if self.recent_sessions:
            for _item_recent_sessions in self.recent_sessions:
                if _item_recent_sessions:
                    _items.append(_item_recent_sessions.to_dict())
            _dict['recentSessions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1DaemonsRoleGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "role": obj.get("role"),
            "description": obj.get("description"),
            "status": obj.get("status"),
            "trigger": V1DaemonsGet200ResponseDaemonsInnerTrigger.from_dict(obj["trigger"]) if obj.get("trigger") is not None else None,
            "stats": V1DaemonsGet200ResponseDaemonsInnerStats.from_dict(obj["stats"]) if obj.get("stats") is not None else None,
            "governance": V1DaemonsPostRequestGovernance.from_dict(obj["governance"]) if obj.get("governance") is not None else None,
            "recentSessions": [V1DaemonsRoleGet200ResponseRecentSessionsInner.from_dict(_item) for _item in obj["recentSessions"]] if obj.get("recentSessions") is not None else None
        })
        return _obj


