# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from paws_client.models.v1_fleet_workers_get200_response_workers_inner_capacity import V1FleetWorkersGet200ResponseWorkersInnerCapacity
from paws_client.models.v1_fleet_workers_get200_response_workers_inner_snapshot import V1FleetWorkersGet200ResponseWorkersInnerSnapshot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1FleetWorkersGet200ResponseWorkersInner(BaseModel):
    """
    V1FleetWorkersGet200ResponseWorkersInner
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)]
    status: StrictStr
    capacity: V1FleetWorkersGet200ResponseWorkersInnerCapacity
    snapshot: V1FleetWorkersGet200ResponseWorkersInnerSnapshot
    uptime: Annotated[int, Field(strict=True, ge=0)]
    __properties: ClassVar[List[str]] = ["name", "status", "capacity", "snapshot", "uptime"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['healthy', 'degraded', 'unhealthy']):
            raise ValueError("must be one of enum values ('healthy', 'degraded', 'unhealthy')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1FleetWorkersGet200ResponseWorkersInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of capacity
        if self.capacity:
            _dict['capacity'] = self.capacity.to_dict()
        # override the default output from pydantic by calling `to_dict()` of snapshot
        if self.snapshot:
            _dict['snapshot'] = self.snapshot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1FleetWorkersGet200ResponseWorkersInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "status": obj.get("status"),
            "capacity": V1FleetWorkersGet200ResponseWorkersInnerCapacity.from_dict(obj["capacity"]) if obj.get("capacity") is not None else None,
            "snapshot": V1FleetWorkersGet200ResponseWorkersInnerSnapshot.from_dict(obj["snapshot"]) if obj.get("snapshot") is not None else None,
            "uptime": obj.get("uptime")
        })
        return _obj


