# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from paws_client.models.v1_sessions_post_request_network import V1SessionsPostRequestNetwork
from paws_client.models.v1_sessions_post_request_resources import V1SessionsPostRequestResources
from paws_client.models.v1_sessions_post_request_workload import V1SessionsPostRequestWorkload
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class V1SessionsPostRequest(BaseModel):
    """
    V1SessionsPostRequest
    """ # noqa: E501
    snapshot: Annotated[str, Field(min_length=1, strict=True)]
    workload: V1SessionsPostRequestWorkload
    resources: Optional[V1SessionsPostRequestResources] = None
    timeout_ms: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=600000, alias="timeoutMs")
    network: Optional[V1SessionsPostRequestNetwork] = None
    callback_url: Optional[StrictStr] = Field(default=None, alias="callbackUrl")
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["snapshot", "workload", "resources", "timeoutMs", "network", "callbackUrl", "metadata"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1SessionsPostRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of workload
        if self.workload:
            _dict['workload'] = self.workload.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict['network'] = self.network.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1SessionsPostRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "snapshot": obj.get("snapshot"),
            "workload": V1SessionsPostRequestWorkload.from_dict(obj["workload"]) if obj.get("workload") is not None else None,
            "resources": V1SessionsPostRequestResources.from_dict(obj["resources"]) if obj.get("resources") is not None else None,
            "timeoutMs": obj.get("timeoutMs") if obj.get("timeoutMs") is not None else 600000,
            "network": V1SessionsPostRequestNetwork.from_dict(obj["network"]) if obj.get("network") is not None else None,
            "callbackUrl": obj.get("callbackUrl"),
            "metadata": obj.get("metadata")
        })
        return _obj


