# coding: utf-8

# flake8: noqa

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "DaemonsApi",
    "FleetApi",
    "HealthApi",
    "SessionsApi",
    "SnapshotsApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HealthGet200Response",
    "V1DaemonsGet200Response",
    "V1DaemonsGet200ResponseDaemonsInner",
    "V1DaemonsGet200ResponseDaemonsInnerStats",
    "V1DaemonsGet200ResponseDaemonsInnerTrigger",
    "V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf",
    "V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf1",
    "V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf2",
    "V1DaemonsPost201Response",
    "V1DaemonsPostRequest",
    "V1DaemonsPostRequestGovernance",
    "V1DaemonsRoleDelete200Response",
    "V1DaemonsRoleGet200Response",
    "V1DaemonsRoleGet200ResponseRecentSessionsInner",
    "V1DaemonsRolePatchRequest",
    "V1FleetGet200Response",
    "V1FleetWorkersGet200Response",
    "V1FleetWorkersGet200ResponseWorkersInner",
    "V1FleetWorkersGet200ResponseWorkersInnerCapacity",
    "V1FleetWorkersGet200ResponseWorkersInnerSnapshot",
    "V1SessionsIdDelete200Response",
    "V1SessionsIdGet200Response",
    "V1SessionsPost202Response",
    "V1SessionsPost400Response",
    "V1SessionsPost400ResponseError",
    "V1SessionsPostRequest",
    "V1SessionsPostRequestNetwork",
    "V1SessionsPostRequestNetworkCredentialsValue",
    "V1SessionsPostRequestResources",
    "V1SessionsPostRequestWorkload",
    "V1SnapshotsBuildsJobIdGet200Response",
    "V1SnapshotsGet200Response",
    "V1SnapshotsGet200ResponseSnapshotsInner",
    "V1SnapshotsGet200ResponseSnapshotsInnerSize",
    "V1SnapshotsIdBuildPost202Response",
    "V1SnapshotsIdBuildPostRequest",
    "V1WebhooksRolePost202Response",
]

# import apis into sdk package
from paws_client.api.daemons_api import DaemonsApi as DaemonsApi
from paws_client.api.fleet_api import FleetApi as FleetApi
from paws_client.api.health_api import HealthApi as HealthApi
from paws_client.api.sessions_api import SessionsApi as SessionsApi
from paws_client.api.snapshots_api import SnapshotsApi as SnapshotsApi
from paws_client.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from paws_client.api_response import ApiResponse as ApiResponse
from paws_client.api_client import ApiClient as ApiClient
from paws_client.configuration import Configuration as Configuration
from paws_client.exceptions import OpenApiException as OpenApiException
from paws_client.exceptions import ApiTypeError as ApiTypeError
from paws_client.exceptions import ApiValueError as ApiValueError
from paws_client.exceptions import ApiKeyError as ApiKeyError
from paws_client.exceptions import ApiAttributeError as ApiAttributeError
from paws_client.exceptions import ApiException as ApiException

# import models into sdk package
from paws_client.models.health_get200_response import HealthGet200Response as HealthGet200Response
from paws_client.models.v1_daemons_get200_response import V1DaemonsGet200Response as V1DaemonsGet200Response
from paws_client.models.v1_daemons_get200_response_daemons_inner import V1DaemonsGet200ResponseDaemonsInner as V1DaemonsGet200ResponseDaemonsInner
from paws_client.models.v1_daemons_get200_response_daemons_inner_stats import V1DaemonsGet200ResponseDaemonsInnerStats as V1DaemonsGet200ResponseDaemonsInnerStats
from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger import V1DaemonsGet200ResponseDaemonsInnerTrigger as V1DaemonsGet200ResponseDaemonsInnerTrigger
from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger_one_of import V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf as V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf
from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger_one_of1 import V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf1 as V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf1
from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger_one_of2 import V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf2 as V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf2
from paws_client.models.v1_daemons_post201_response import V1DaemonsPost201Response as V1DaemonsPost201Response
from paws_client.models.v1_daemons_post_request import V1DaemonsPostRequest as V1DaemonsPostRequest
from paws_client.models.v1_daemons_post_request_governance import V1DaemonsPostRequestGovernance as V1DaemonsPostRequestGovernance
from paws_client.models.v1_daemons_role_delete200_response import V1DaemonsRoleDelete200Response as V1DaemonsRoleDelete200Response
from paws_client.models.v1_daemons_role_get200_response import V1DaemonsRoleGet200Response as V1DaemonsRoleGet200Response
from paws_client.models.v1_daemons_role_get200_response_recent_sessions_inner import V1DaemonsRoleGet200ResponseRecentSessionsInner as V1DaemonsRoleGet200ResponseRecentSessionsInner
from paws_client.models.v1_daemons_role_patch_request import V1DaemonsRolePatchRequest as V1DaemonsRolePatchRequest
from paws_client.models.v1_fleet_get200_response import V1FleetGet200Response as V1FleetGet200Response
from paws_client.models.v1_fleet_workers_get200_response import V1FleetWorkersGet200Response as V1FleetWorkersGet200Response
from paws_client.models.v1_fleet_workers_get200_response_workers_inner import V1FleetWorkersGet200ResponseWorkersInner as V1FleetWorkersGet200ResponseWorkersInner
from paws_client.models.v1_fleet_workers_get200_response_workers_inner_capacity import V1FleetWorkersGet200ResponseWorkersInnerCapacity as V1FleetWorkersGet200ResponseWorkersInnerCapacity
from paws_client.models.v1_fleet_workers_get200_response_workers_inner_snapshot import V1FleetWorkersGet200ResponseWorkersInnerSnapshot as V1FleetWorkersGet200ResponseWorkersInnerSnapshot
from paws_client.models.v1_sessions_id_delete200_response import V1SessionsIdDelete200Response as V1SessionsIdDelete200Response
from paws_client.models.v1_sessions_id_get200_response import V1SessionsIdGet200Response as V1SessionsIdGet200Response
from paws_client.models.v1_sessions_post202_response import V1SessionsPost202Response as V1SessionsPost202Response
from paws_client.models.v1_sessions_post400_response import V1SessionsPost400Response as V1SessionsPost400Response
from paws_client.models.v1_sessions_post400_response_error import V1SessionsPost400ResponseError as V1SessionsPost400ResponseError
from paws_client.models.v1_sessions_post_request import V1SessionsPostRequest as V1SessionsPostRequest
from paws_client.models.v1_sessions_post_request_network import V1SessionsPostRequestNetwork as V1SessionsPostRequestNetwork
from paws_client.models.v1_sessions_post_request_network_credentials_value import V1SessionsPostRequestNetworkCredentialsValue as V1SessionsPostRequestNetworkCredentialsValue
from paws_client.models.v1_sessions_post_request_resources import V1SessionsPostRequestResources as V1SessionsPostRequestResources
from paws_client.models.v1_sessions_post_request_workload import V1SessionsPostRequestWorkload as V1SessionsPostRequestWorkload
from paws_client.models.v1_snapshots_builds_job_id_get200_response import V1SnapshotsBuildsJobIdGet200Response as V1SnapshotsBuildsJobIdGet200Response
from paws_client.models.v1_snapshots_get200_response import V1SnapshotsGet200Response as V1SnapshotsGet200Response
from paws_client.models.v1_snapshots_get200_response_snapshots_inner import V1SnapshotsGet200ResponseSnapshotsInner as V1SnapshotsGet200ResponseSnapshotsInner
from paws_client.models.v1_snapshots_get200_response_snapshots_inner_size import V1SnapshotsGet200ResponseSnapshotsInnerSize as V1SnapshotsGet200ResponseSnapshotsInnerSize
from paws_client.models.v1_snapshots_id_build_post202_response import V1SnapshotsIdBuildPost202Response as V1SnapshotsIdBuildPost202Response
from paws_client.models.v1_snapshots_id_build_post_request import V1SnapshotsIdBuildPostRequest as V1SnapshotsIdBuildPostRequest
from paws_client.models.v1_webhooks_role_post202_response import V1WebhooksRolePost202Response as V1WebhooksRolePost202Response

