#!/bin/bash
# /\_/\
# ( o.o )  paws installer
#  > ^ <
#
# Usage:
#   curl -fsSL https://getpaws.dev/install.sh | bash
#
# What it does:
#   1. Installs Docker (if missing)
#   2. Downloads paws
#   3. Generates secrets
#   4. Starts the stack
#   5. Dashboard available at http://YOUR_IP:3000
#
# Domain + HTTPS configured later from the dashboard settings page.

set -euo pipefail

PAWS_DIR="/opt/paws"
GITHUB_REPO="arek-e/paws"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_cat() {
  echo ""
  echo -e "${GREEN} /\\_/\\"
  echo -e "( o.o )  $1"
  echo -e " > ^ <${NC}"
  echo ""
}

info() { echo -e "${CYAN}==> $1${NC}"; }
warn() { echo -e "${YELLOW}⚠  $1${NC}"; }
error() { echo -e "${RED}✗  $1${NC}"; exit 1; }
ok() { echo -e "${GREEN}✓  $1${NC}"; }

print_cat "paws installer"

# ── Check root ─────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  error "Please run as root: curl ... | sudo bash"
fi

# ── Install Docker ─────────────────────────────────────────────────────────
if command -v docker &>/dev/null; then
  ok "Docker installed"
else
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker && systemctl start docker
  ok "Docker installed"
fi

docker compose version &>/dev/null || error "Docker Compose v2 required"

# ── Get server IP ─────────────────────────────────────────────────────────
SERVER_IP=$(curl -s4 ifconfig.me 2>/dev/null || curl -s4 icanhazip.com 2>/dev/null || echo "localhost")

# ── Download paws ─────────────────────────────────────────────────────────
info "Downloading paws..."

# Try release tarball first, fall back to git clone
VERSION=$(curl -sf "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" 2>/dev/null | grep -o '"tag_name":"[^"]*"' | cut -d'"' -f4 || true)
VERSION="${VERSION#v}"

if [[ -n "$VERSION" ]]; then
  TARBALL="https://github.com/${GITHUB_REPO}/releases/download/v${VERSION}/paws-v${VERSION}.tar.gz"
  mkdir -p "$PAWS_DIR"
  if curl -fSL "$TARBALL" -o /tmp/paws.tar.gz 2>/dev/null; then
    tar -xzf /tmp/paws.tar.gz -C "$PAWS_DIR" && rm -f /tmp/paws.tar.gz
    ok "Downloaded paws v${VERSION}"
  fi
fi

if [[ ! -f "${PAWS_DIR}/docker-compose.yml" ]]; then
  # No release — clone repo
  if ! command -v git &>/dev/null; then
    apt-get update -qq && apt-get install -y -qq git 2>/dev/null || yum install -y git 2>/dev/null || true
  fi
  git clone --depth 1 "https://github.com/${GITHUB_REPO}.git" "$PAWS_DIR" 2>/dev/null || true
  VERSION="dev"
fi

cd "$PAWS_DIR"

# ── Generate secrets ──────────────────────────────────────────────────────
info "Generating configuration..."

API_KEY=$(openssl rand -hex 24)

cat > .env << EOF
# Generated by paws installer
API_KEY=${API_KEY}
GRAFANA_ADMIN_PASSWORD=$(openssl rand -hex 16)
LLM_GATEWAY=
LLM_GATEWAY_URL=
LLM_GATEWAY_KEY=
EOF

# ── Generate Dex config (minimal, OIDC enabled later with domain) ─────────
mkdir -p config/dex
cat > config/dex/config.yaml << EOF
issuer: http://${SERVER_IP}:3000/dex

storage:
  type: sqlite3
  config:
    file: /data/dex.db

web:
  http: 0.0.0.0:5556

enablePasswordDB: true
EOF

# ── Start ─────────────────────────────────────────────────────────────────
info "Starting paws..."
docker compose build gateway 2>&1 | tail -3
docker compose up -d

# Install CLI
[[ -f scripts/update.sh ]] && cp scripts/update.sh /usr/local/bin/paws && chmod +x /usr/local/bin/paws

# Wait for gateway health
info "Waiting for startup..."
for i in $(seq 1 30); do
  if curl -sf "http://localhost:3000/health" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

# ── Done ──────────────────────────────────────────────────────────────────
echo ""
print_cat "paws is running!"
echo -e "  ${GREEN}Dashboard${NC}   http://${SERVER_IP}:3000"
echo -e "  ${CYAN}API Key${NC}     ${API_KEY}"
echo ""
echo -e "  Configure a domain later from ${GREEN}Settings${NC} in the dashboard."
echo ""
echo -e "  ${CYAN}Update${NC}      paws update"
echo -e "  ${CYAN}Logs${NC}        cd /opt/paws && docker compose logs -f"
echo ""
