apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: paws
  labels:
    app.kubernetes.io/name: paws
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paws
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
