# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_post_request_governance import V1DaemonsPostRequestGovernance

class TestV1DaemonsPostRequestGovernance(unittest.TestCase):
    """V1DaemonsPostRequestGovernance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsPostRequestGovernance:
        """Test V1DaemonsPostRequestGovernance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsPostRequestGovernance`
        """
        model = V1DaemonsPostRequestGovernance()
        if include_optional:
            return V1DaemonsPostRequestGovernance(
                max_actions_per_hour = 0,
                requires_approval = [
                    ''
                    ],
                audit_log = True
            )
        else:
            return V1DaemonsPostRequestGovernance(
        )
        """

    def testV1DaemonsPostRequestGovernance(self):
        """Test V1DaemonsPostRequestGovernance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
