# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post_request_network import V1SessionsPostRequestNetwork

class TestV1SessionsPostRequestNetwork(unittest.TestCase):
    """V1SessionsPostRequestNetwork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPostRequestNetwork:
        """Test V1SessionsPostRequestNetwork
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPostRequestNetwork`
        """
        model = V1SessionsPostRequestNetwork()
        if include_optional:
            return V1SessionsPostRequestNetwork(
                allow_out = [
                    ''
                    ],
                credentials = {
                    'key' : paws_client.models._v1_sessions_post_request_network_credentials_value._v1_sessions_post_request_network_credentials_value(
                        headers = {
                            'key' : ''
                            }, )
                    }
            )
        else:
            return V1SessionsPostRequestNetwork(
        )
        """

    def testV1SessionsPostRequestNetwork(self):
        """Test V1SessionsPostRequestNetwork"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
