# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.health_get200_response import HealthGet200Response

class TestHealthGet200Response(unittest.TestCase):
    """HealthGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthGet200Response:
        """Test HealthGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthGet200Response`
        """
        model = HealthGet200Response()
        if include_optional:
            return HealthGet200Response(
                status = '',
                uptime = 1.337,
                version = ''
            )
        else:
            return HealthGet200Response(
                status = '',
                uptime = 1.337,
                version = '',
        )
        """

    def testHealthGet200Response(self):
        """Test HealthGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
