# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_snapshots_builds_job_id_get200_response import V1SnapshotsBuildsJobIdGet200Response

class TestV1SnapshotsBuildsJobIdGet200Response(unittest.TestCase):
    """V1SnapshotsBuildsJobIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SnapshotsBuildsJobIdGet200Response:
        """Test V1SnapshotsBuildsJobIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SnapshotsBuildsJobIdGet200Response`
        """
        model = V1SnapshotsBuildsJobIdGet200Response()
        if include_optional:
            return V1SnapshotsBuildsJobIdGet200Response(
                job_id = '0',
                snapshot_id = '0',
                status = 'building',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = ''
            )
        else:
            return V1SnapshotsBuildsJobIdGet200Response(
                job_id = '0',
                snapshot_id = '0',
                status = 'building',
        )
        """

    def testV1SnapshotsBuildsJobIdGet200Response(self):
        """Test V1SnapshotsBuildsJobIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
