# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_snapshots_get200_response_snapshots_inner_size import V1SnapshotsGet200ResponseSnapshotsInnerSize

class TestV1SnapshotsGet200ResponseSnapshotsInnerSize(unittest.TestCase):
    """V1SnapshotsGet200ResponseSnapshotsInnerSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SnapshotsGet200ResponseSnapshotsInnerSize:
        """Test V1SnapshotsGet200ResponseSnapshotsInnerSize
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SnapshotsGet200ResponseSnapshotsInnerSize`
        """
        model = V1SnapshotsGet200ResponseSnapshotsInnerSize()
        if include_optional:
            return V1SnapshotsGet200ResponseSnapshotsInnerSize(
                disk = '',
                memory = '',
                total = ''
            )
        else:
            return V1SnapshotsGet200ResponseSnapshotsInnerSize(
                disk = '',
                memory = '',
                total = '',
        )
        """

    def testV1SnapshotsGet200ResponseSnapshotsInnerSize(self):
        """Test V1SnapshotsGet200ResponseSnapshotsInnerSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
