# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_sessions_id_delete(self) -> None:
        """Test case for v1_sessions_id_delete

        """
        pass

    def test_v1_sessions_id_get(self) -> None:
        """Test case for v1_sessions_id_get

        """
        pass

    def test_v1_sessions_post(self) -> None:
        """Test case for v1_sessions_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
