# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_role_get200_response_recent_sessions_inner import V1DaemonsRoleGet200ResponseRecentSessionsInner

class TestV1DaemonsRoleGet200ResponseRecentSessionsInner(unittest.TestCase):
    """V1DaemonsRoleGet200ResponseRecentSessionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsRoleGet200ResponseRecentSessionsInner:
        """Test V1DaemonsRoleGet200ResponseRecentSessionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsRoleGet200ResponseRecentSessionsInner`
        """
        model = V1DaemonsRoleGet200ResponseRecentSessionsInner()
        if include_optional:
            return V1DaemonsRoleGet200ResponseRecentSessionsInner(
                session_id = '',
                triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'pending',
                duration_ms = 0
            )
        else:
            return V1DaemonsRoleGet200ResponseRecentSessionsInner(
                session_id = '',
                triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status = 'pending',
        )
        """

    def testV1DaemonsRoleGet200ResponseRecentSessionsInner(self):
        """Test V1DaemonsRoleGet200ResponseRecentSessionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
