# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_role_patch_request import V1DaemonsRolePatchRequest

class TestV1DaemonsRolePatchRequest(unittest.TestCase):
    """V1DaemonsRolePatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsRolePatchRequest:
        """Test V1DaemonsRolePatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsRolePatchRequest`
        """
        model = V1DaemonsRolePatchRequest()
        if include_optional:
            return V1DaemonsRolePatchRequest(
                description = '',
                trigger = None,
                workload = paws_client.models._v1_sessions_post_request_workload._v1_sessions_post_request_workload(
                    type = 'script', 
                    script = '0', 
                    env = {
                        'key' : ''
                        }, ),
                resources = paws_client.models._v1_sessions_post_request_resources._v1_sessions_post_request_resources(
                    vcpus = 1, 
                    memory_mb = 256, ),
                network = paws_client.models._v1_sessions_post_request_network._v1_sessions_post_request_network(
                    allow_out = [
                        ''
                        ], 
                    credentials = {
                        'key' : paws_client.models._v1_sessions_post_request_network_credentials_value._v1_sessions_post_request_network_credentials_value(
                            headers = {
                                'key' : ''
                                }, )
                        }, ),
                governance = paws_client.models._v1_daemons_post_request_governance._v1_daemons_post_request_governance(
                    max_actions_per_hour = 0, 
                    requires_approval = [
                        ''
                        ], 
                    audit_log = True, )
            )
        else:
            return V1DaemonsRolePatchRequest(
        )
        """

    def testV1DaemonsRolePatchRequest(self):
        """Test V1DaemonsRolePatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
