# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.api.daemons_api import DaemonsApi


class TestDaemonsApi(unittest.TestCase):
    """DaemonsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DaemonsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_daemons_get(self) -> None:
        """Test case for v1_daemons_get

        """
        pass

    def test_v1_daemons_post(self) -> None:
        """Test case for v1_daemons_post

        """
        pass

    def test_v1_daemons_role_delete(self) -> None:
        """Test case for v1_daemons_role_delete

        """
        pass

    def test_v1_daemons_role_get(self) -> None:
        """Test case for v1_daemons_role_get

        """
        pass

    def test_v1_daemons_role_patch(self) -> None:
        """Test case for v1_daemons_role_patch

        """
        pass


if __name__ == '__main__':
    unittest.main()
