# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_role_delete200_response import V1DaemonsRoleDelete200Response

class TestV1DaemonsRoleDelete200Response(unittest.TestCase):
    """V1DaemonsRoleDelete200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsRoleDelete200Response:
        """Test V1DaemonsRoleDelete200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsRoleDelete200Response`
        """
        model = V1DaemonsRoleDelete200Response()
        if include_optional:
            return V1DaemonsRoleDelete200Response(
                role = '',
                status = 'stopped'
            )
        else:
            return V1DaemonsRoleDelete200Response(
                role = '',
                status = 'stopped',
        )
        """

    def testV1DaemonsRoleDelete200Response(self):
        """Test V1DaemonsRoleDelete200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
