# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_get200_response import V1DaemonsGet200Response

class TestV1DaemonsGet200Response(unittest.TestCase):
    """V1DaemonsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsGet200Response:
        """Test V1DaemonsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsGet200Response`
        """
        model = V1DaemonsGet200Response()
        if include_optional:
            return V1DaemonsGet200Response(
                daemons = [
                    paws_client.models._v1_daemons_get_200_response_daemons_inner._v1_daemons_get_200_response_daemons_inner(
                        role = '0', 
                        description = '', 
                        status = 'active', 
                        trigger = null, 
                        stats = paws_client.models._v1_daemons_get_200_response_daemons_inner_stats._v1_daemons_get_200_response_daemons_inner_stats(
                            total_invocations = 0, 
                            last_invoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            avg_duration_ms = 0, ), )
                    ]
            )
        else:
            return V1DaemonsGet200Response(
                daemons = [
                    paws_client.models._v1_daemons_get_200_response_daemons_inner._v1_daemons_get_200_response_daemons_inner(
                        role = '0', 
                        description = '', 
                        status = 'active', 
                        trigger = null, 
                        stats = paws_client.models._v1_daemons_get_200_response_daemons_inner_stats._v1_daemons_get_200_response_daemons_inner_stats(
                            total_invocations = 0, 
                            last_invoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            avg_duration_ms = 0, ), )
                    ],
        )
        """

    def testV1DaemonsGet200Response(self):
        """Test V1DaemonsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
