# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_fleet_workers_get200_response_workers_inner import V1FleetWorkersGet200ResponseWorkersInner

class TestV1FleetWorkersGet200ResponseWorkersInner(unittest.TestCase):
    """V1FleetWorkersGet200ResponseWorkersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FleetWorkersGet200ResponseWorkersInner:
        """Test V1FleetWorkersGet200ResponseWorkersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FleetWorkersGet200ResponseWorkersInner`
        """
        model = V1FleetWorkersGet200ResponseWorkersInner()
        if include_optional:
            return V1FleetWorkersGet200ResponseWorkersInner(
                name = '0',
                status = 'healthy',
                capacity = paws_client.models._v1_fleet_workers_get_200_response_workers_inner_capacity._v1_fleet_workers_get_200_response_workers_inner_capacity(
                    max_concurrent = 0, 
                    running = 0, 
                    queued = 0, 
                    available = 0, ),
                snapshot = paws_client.models._v1_fleet_workers_get_200_response_workers_inner_snapshot._v1_fleet_workers_get_200_response_workers_inner_snapshot(
                    id = '0', 
                    version = 0, 
                    age_ms = 0, ),
                uptime = 0
            )
        else:
            return V1FleetWorkersGet200ResponseWorkersInner(
                name = '0',
                status = 'healthy',
                capacity = paws_client.models._v1_fleet_workers_get_200_response_workers_inner_capacity._v1_fleet_workers_get_200_response_workers_inner_capacity(
                    max_concurrent = 0, 
                    running = 0, 
                    queued = 0, 
                    available = 0, ),
                snapshot = paws_client.models._v1_fleet_workers_get_200_response_workers_inner_snapshot._v1_fleet_workers_get_200_response_workers_inner_snapshot(
                    id = '0', 
                    version = 0, 
                    age_ms = 0, ),
                uptime = 0,
        )
        """

    def testV1FleetWorkersGet200ResponseWorkersInner(self):
        """Test V1FleetWorkersGet200ResponseWorkersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
