# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.api.snapshots_api import SnapshotsApi


class TestSnapshotsApi(unittest.TestCase):
    """SnapshotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SnapshotsApi()

    def tearDown(self) -> None:
        pass

    def test_v1_snapshots_builds_job_id_get(self) -> None:
        """Test case for v1_snapshots_builds_job_id_get

        """
        pass

    def test_v1_snapshots_get(self) -> None:
        """Test case for v1_snapshots_get

        """
        pass

    def test_v1_snapshots_id_build_post(self) -> None:
        """Test case for v1_snapshots_id_build_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
