# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger_one_of import V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf

class TestV1DaemonsGet200ResponseDaemonsInnerTriggerOneOf(unittest.TestCase):
    """V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf:
        """Test V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf`
        """
        model = V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf()
        if include_optional:
            return V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf(
                type = 'webhook',
                events = [
                    '0'
                    ],
                secret = ''
            )
        else:
            return V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf(
                type = 'webhook',
                events = [
                    '0'
                    ],
        )
        """

    def testV1DaemonsGet200ResponseDaemonsInnerTriggerOneOf(self):
        """Test V1DaemonsGet200ResponseDaemonsInnerTriggerOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
