# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post_request_resources import V1SessionsPostRequestResources

class TestV1SessionsPostRequestResources(unittest.TestCase):
    """V1SessionsPostRequestResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPostRequestResources:
        """Test V1SessionsPostRequestResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPostRequestResources`
        """
        model = V1SessionsPostRequestResources()
        if include_optional:
            return V1SessionsPostRequestResources(
                vcpus = 1,
                memory_mb = 256
            )
        else:
            return V1SessionsPostRequestResources(
        )
        """

    def testV1SessionsPostRequestResources(self):
        """Test V1SessionsPostRequestResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
