# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_snapshots_id_build_post_request import V1SnapshotsIdBuildPostRequest

class TestV1SnapshotsIdBuildPostRequest(unittest.TestCase):
    """V1SnapshotsIdBuildPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SnapshotsIdBuildPostRequest:
        """Test V1SnapshotsIdBuildPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SnapshotsIdBuildPostRequest`
        """
        model = V1SnapshotsIdBuildPostRequest()
        if include_optional:
            return V1SnapshotsIdBuildPostRequest(
                base = '0',
                setup = '',
                resources = paws_client.models._v1_sessions_post_request_resources._v1_sessions_post_request_resources(
                    vcpus = 1, 
                    memory_mb = 256, )
            )
        else:
            return V1SnapshotsIdBuildPostRequest(
                base = '0',
                setup = '',
        )
        """

    def testV1SnapshotsIdBuildPostRequest(self):
        """Test V1SnapshotsIdBuildPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
