# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_fleet_get200_response import V1FleetGet200Response

class TestV1FleetGet200Response(unittest.TestCase):
    """V1FleetGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FleetGet200Response:
        """Test V1FleetGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FleetGet200Response`
        """
        model = V1FleetGet200Response()
        if include_optional:
            return V1FleetGet200Response(
                total_workers = 0,
                healthy_workers = 0,
                total_capacity = 0,
                used_capacity = 0,
                queued_sessions = 0,
                active_daemons = 0,
                active_sessions = 0
            )
        else:
            return V1FleetGet200Response(
                total_workers = 0,
                healthy_workers = 0,
                total_capacity = 0,
                used_capacity = 0,
                queued_sessions = 0,
                active_daemons = 0,
                active_sessions = 0,
        )
        """

    def testV1FleetGet200Response(self):
        """Test V1FleetGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
