# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post400_response import V1SessionsPost400Response

class TestV1SessionsPost400Response(unittest.TestCase):
    """V1SessionsPost400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPost400Response:
        """Test V1SessionsPost400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPost400Response`
        """
        model = V1SessionsPost400Response()
        if include_optional:
            return V1SessionsPost400Response(
                error = paws_client.models._v1_sessions_post_400_response_error._v1_sessions_post_400_response_error(
                    code = 'UNAUTHORIZED', 
                    message = '', )
            )
        else:
            return V1SessionsPost400Response(
                error = paws_client.models._v1_sessions_post_400_response_error._v1_sessions_post_400_response_error(
                    code = 'UNAUTHORIZED', 
                    message = '', ),
        )
        """

    def testV1SessionsPost400Response(self):
        """Test V1SessionsPost400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
