# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_fleet_workers_get200_response_workers_inner_capacity import V1FleetWorkersGet200ResponseWorkersInnerCapacity

class TestV1FleetWorkersGet200ResponseWorkersInnerCapacity(unittest.TestCase):
    """V1FleetWorkersGet200ResponseWorkersInnerCapacity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FleetWorkersGet200ResponseWorkersInnerCapacity:
        """Test V1FleetWorkersGet200ResponseWorkersInnerCapacity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FleetWorkersGet200ResponseWorkersInnerCapacity`
        """
        model = V1FleetWorkersGet200ResponseWorkersInnerCapacity()
        if include_optional:
            return V1FleetWorkersGet200ResponseWorkersInnerCapacity(
                max_concurrent = 0,
                running = 0,
                queued = 0,
                available = 0
            )
        else:
            return V1FleetWorkersGet200ResponseWorkersInnerCapacity(
                max_concurrent = 0,
                running = 0,
                queued = 0,
                available = 0,
        )
        """

    def testV1FleetWorkersGet200ResponseWorkersInnerCapacity(self):
        """Test V1FleetWorkersGet200ResponseWorkersInnerCapacity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
