# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_id_delete200_response import V1SessionsIdDelete200Response

class TestV1SessionsIdDelete200Response(unittest.TestCase):
    """V1SessionsIdDelete200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsIdDelete200Response:
        """Test V1SessionsIdDelete200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsIdDelete200Response`
        """
        model = V1SessionsIdDelete200Response()
        if include_optional:
            return V1SessionsIdDelete200Response(
                session_id = '',
                status = 'cancelled'
            )
        else:
            return V1SessionsIdDelete200Response(
                session_id = '',
                status = 'cancelled',
        )
        """

    def testV1SessionsIdDelete200Response(self):
        """Test V1SessionsIdDelete200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
