# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post_request_workload import V1SessionsPostRequestWorkload

class TestV1SessionsPostRequestWorkload(unittest.TestCase):
    """V1SessionsPostRequestWorkload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPostRequestWorkload:
        """Test V1SessionsPostRequestWorkload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPostRequestWorkload`
        """
        model = V1SessionsPostRequestWorkload()
        if include_optional:
            return V1SessionsPostRequestWorkload(
                type = 'script',
                script = '0',
                env = {
                    'key' : ''
                    }
            )
        else:
            return V1SessionsPostRequestWorkload(
                type = 'script',
                script = '0',
        )
        """

    def testV1SessionsPostRequestWorkload(self):
        """Test V1SessionsPostRequestWorkload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
