# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_snapshots_id_build_post202_response import V1SnapshotsIdBuildPost202Response

class TestV1SnapshotsIdBuildPost202Response(unittest.TestCase):
    """V1SnapshotsIdBuildPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SnapshotsIdBuildPost202Response:
        """Test V1SnapshotsIdBuildPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SnapshotsIdBuildPost202Response`
        """
        model = V1SnapshotsIdBuildPost202Response()
        if include_optional:
            return V1SnapshotsIdBuildPost202Response(
                snapshot_id = '0',
                status = 'building',
                job_id = '0'
            )
        else:
            return V1SnapshotsIdBuildPost202Response(
                snapshot_id = '0',
                status = 'building',
                job_id = '0',
        )
        """

    def testV1SnapshotsIdBuildPost202Response(self):
        """Test V1SnapshotsIdBuildPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
