# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_get200_response_daemons_inner_trigger import V1DaemonsGet200ResponseDaemonsInnerTrigger

class TestV1DaemonsGet200ResponseDaemonsInnerTrigger(unittest.TestCase):
    """V1DaemonsGet200ResponseDaemonsInnerTrigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsGet200ResponseDaemonsInnerTrigger:
        """Test V1DaemonsGet200ResponseDaemonsInnerTrigger
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsGet200ResponseDaemonsInnerTrigger`
        """
        model = V1DaemonsGet200ResponseDaemonsInnerTrigger()
        if include_optional:
            return V1DaemonsGet200ResponseDaemonsInnerTrigger(
                type = 'webhook',
                events = [
                    '0'
                    ],
                secret = '',
                cron = '0',
                condition = '0',
                interval_ms = 0
            )
        else:
            return V1DaemonsGet200ResponseDaemonsInnerTrigger(
                type = 'webhook',
                events = [
                    '0'
                    ],
                cron = '0',
                condition = '0',
        )
        """

    def testV1DaemonsGet200ResponseDaemonsInnerTrigger(self):
        """Test V1DaemonsGet200ResponseDaemonsInnerTrigger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
