# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.api.fleet_api import FleetApi


class TestFleetApi(unittest.TestCase):
    """FleetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FleetApi()

    def tearDown(self) -> None:
        pass

    def test_v1_fleet_get(self) -> None:
        """Test case for v1_fleet_get

        """
        pass

    def test_v1_fleet_workers_get(self) -> None:
        """Test case for v1_fleet_workers_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
