# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_fleet_workers_get200_response_workers_inner_snapshot import V1FleetWorkersGet200ResponseWorkersInnerSnapshot

class TestV1FleetWorkersGet200ResponseWorkersInnerSnapshot(unittest.TestCase):
    """V1FleetWorkersGet200ResponseWorkersInnerSnapshot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FleetWorkersGet200ResponseWorkersInnerSnapshot:
        """Test V1FleetWorkersGet200ResponseWorkersInnerSnapshot
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FleetWorkersGet200ResponseWorkersInnerSnapshot`
        """
        model = V1FleetWorkersGet200ResponseWorkersInnerSnapshot()
        if include_optional:
            return V1FleetWorkersGet200ResponseWorkersInnerSnapshot(
                id = '0',
                version = 0,
                age_ms = 0
            )
        else:
            return V1FleetWorkersGet200ResponseWorkersInnerSnapshot(
                id = '0',
                version = 0,
                age_ms = 0,
        )
        """

    def testV1FleetWorkersGet200ResponseWorkersInnerSnapshot(self):
        """Test V1FleetWorkersGet200ResponseWorkersInnerSnapshot"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
