# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_snapshots_get200_response import V1SnapshotsGet200Response

class TestV1SnapshotsGet200Response(unittest.TestCase):
    """V1SnapshotsGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SnapshotsGet200Response:
        """Test V1SnapshotsGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SnapshotsGet200Response`
        """
        model = V1SnapshotsGet200Response()
        if include_optional:
            return V1SnapshotsGet200Response(
                snapshots = [
                    paws_client.models._v1_snapshots_get_200_response_snapshots_inner._v1_snapshots_get_200_response_snapshots_inner(
                        id = '0', 
                        version = 0, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        size = paws_client.models._v1_snapshots_get_200_response_snapshots_inner_size._v1_snapshots_get_200_response_snapshots_inner_size(
                            disk = '', 
                            memory = '', 
                            total = '', ), 
                        config = paws_client.models._v1_sessions_post_request_resources._v1_sessions_post_request_resources(
                            vcpus = 1, 
                            memory_mb = 256, ), )
                    ]
            )
        else:
            return V1SnapshotsGet200Response(
                snapshots = [
                    paws_client.models._v1_snapshots_get_200_response_snapshots_inner._v1_snapshots_get_200_response_snapshots_inner(
                        id = '0', 
                        version = 0, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        size = paws_client.models._v1_snapshots_get_200_response_snapshots_inner_size._v1_snapshots_get_200_response_snapshots_inner_size(
                            disk = '', 
                            memory = '', 
                            total = '', ), 
                        config = paws_client.models._v1_sessions_post_request_resources._v1_sessions_post_request_resources(
                            vcpus = 1, 
                            memory_mb = 256, ), )
                    ],
        )
        """

    def testV1SnapshotsGet200Response(self):
        """Test V1SnapshotsGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
