# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_id_get200_response import V1SessionsIdGet200Response

class TestV1SessionsIdGet200Response(unittest.TestCase):
    """V1SessionsIdGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsIdGet200Response:
        """Test V1SessionsIdGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsIdGet200Response`
        """
        model = V1SessionsIdGet200Response()
        if include_optional:
            return V1SessionsIdGet200Response(
                session_id = '',
                status = 'pending',
                exit_code = 56,
                stdout = '',
                stderr = '',
                output = None,
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                duration_ms = 0,
                worker = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return V1SessionsIdGet200Response(
                session_id = '',
                status = 'pending',
        )
        """

    def testV1SessionsIdGet200Response(self):
        """Test V1SessionsIdGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
