# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_daemons_role_get200_response import V1DaemonsRoleGet200Response

class TestV1DaemonsRoleGet200Response(unittest.TestCase):
    """V1DaemonsRoleGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonsRoleGet200Response:
        """Test V1DaemonsRoleGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonsRoleGet200Response`
        """
        model = V1DaemonsRoleGet200Response()
        if include_optional:
            return V1DaemonsRoleGet200Response(
                role = '0',
                description = '',
                status = 'active',
                trigger = None,
                stats = paws_client.models._v1_daemons_get_200_response_daemons_inner_stats._v1_daemons_get_200_response_daemons_inner_stats(
                    total_invocations = 0, 
                    last_invoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    avg_duration_ms = 0, ),
                governance = paws_client.models._v1_daemons_post_request_governance._v1_daemons_post_request_governance(
                    max_actions_per_hour = 0, 
                    requires_approval = [
                        ''
                        ], 
                    audit_log = True, ),
                recent_sessions = [
                    paws_client.models._v1_daemons__role__get_200_response_recent_sessions_inner._v1_daemons__role__get_200_response_recentSessions_inner(
                        session_id = '', 
                        triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'pending', 
                        duration_ms = 0, )
                    ]
            )
        else:
            return V1DaemonsRoleGet200Response(
                role = '0',
                description = '',
                status = 'active',
                trigger = None,
                stats = paws_client.models._v1_daemons_get_200_response_daemons_inner_stats._v1_daemons_get_200_response_daemons_inner_stats(
                    total_invocations = 0, 
                    last_invoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    avg_duration_ms = 0, ),
                governance = paws_client.models._v1_daemons_post_request_governance._v1_daemons_post_request_governance(
                    max_actions_per_hour = 0, 
                    requires_approval = [
                        ''
                        ], 
                    audit_log = True, ),
                recent_sessions = [
                    paws_client.models._v1_daemons__role__get_200_response_recent_sessions_inner._v1_daemons__role__get_200_response_recentSessions_inner(
                        session_id = '', 
                        triggered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = 'pending', 
                        duration_ms = 0, )
                    ],
        )
        """

    def testV1DaemonsRoleGet200Response(self):
        """Test V1DaemonsRoleGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
