# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post202_response import V1SessionsPost202Response

class TestV1SessionsPost202Response(unittest.TestCase):
    """V1SessionsPost202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPost202Response:
        """Test V1SessionsPost202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPost202Response`
        """
        model = V1SessionsPost202Response()
        if include_optional:
            return V1SessionsPost202Response(
                session_id = '',
                status = 'pending'
            )
        else:
            return V1SessionsPost202Response(
                session_id = '',
                status = 'pending',
        )
        """

    def testV1SessionsPost202Response(self):
        """Test V1SessionsPost202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
