# coding: utf-8

"""
    paws Gateway API

    Self-hosted platform for running AI agents in isolated Firecracker microVMs

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from paws_client.models.v1_sessions_post400_response_error import V1SessionsPost400ResponseError

class TestV1SessionsPost400ResponseError(unittest.TestCase):
    """V1SessionsPost400ResponseError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SessionsPost400ResponseError:
        """Test V1SessionsPost400ResponseError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SessionsPost400ResponseError`
        """
        model = V1SessionsPost400ResponseError()
        if include_optional:
            return V1SessionsPost400ResponseError(
                code = 'UNAUTHORIZED',
                message = ''
            )
        else:
            return V1SessionsPost400ResponseError(
                code = 'UNAUTHORIZED',
                message = '',
        )
        """

    def testV1SessionsPost400ResponseError(self):
        """Test V1SessionsPost400ResponseError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
