apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac/serviceaccount.yaml
  - rbac/clusterrole.yaml
  - control-plane/configmap.yaml
  - control-plane/deployment.yaml
  - control-plane/service.yaml
  - worker/configmap.yaml
  - worker/daemonset.yaml
  - worker/service.yaml

images:
  - name: ghcr.io/arek-e/paws-control-plane
    newTag: latest
  - name: ghcr.io/arek-e/paws-worker
    newTag: latest
