apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: paws
  labels:
    app.kubernetes.io/name: paws
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: paws
    app.kubernetes.io/component: worker
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
